'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class NewPatient

   '''<summary>
   '''inputNRIC control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents inputNRIC As Global.System.Web.UI.HtmlControls.HtmlInputText

   '''<summary>
   '''inputName control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents inputName As Global.System.Web.UI.HtmlControls.HtmlInputText

   '''<summary>
   '''inputDOB control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents inputDOB As Global.System.Web.UI.HtmlControls.HtmlInputGenericControl

   '''<summary>
   '''inputAddress control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents inputAddress As Global.System.Web.UI.HtmlControls.HtmlInputText

   '''<summary>
   '''inputPhone control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents inputPhone As Global.System.Web.UI.HtmlControls.HtmlInputText

   '''<summary>
   '''pictureUpload control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents pictureUpload As Global.System.Web.UI.WebControls.FileUpload

   '''<summary>
   '''showImg control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents showImg As Global.System.Web.UI.HtmlControls.HtmlButton

   '''<summary>
   '''pictureImg control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents pictureImg As Global.System.Web.UI.HtmlControls.HtmlImage
End Class
