'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class NewClinic

   '''<summary>
   '''inputName control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents inputName As Global.System.Web.UI.HtmlControls.HtmlInputText

   '''<summary>
   '''inputAddress control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents inputAddress As Global.System.Web.UI.HtmlControls.HtmlInputText

   '''<summary>
   '''inputPhone control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents inputPhone As Global.System.Web.UI.HtmlControls.HtmlInputText
End Class
