'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class EditTreatment

   '''<summary>
   '''hiddenTreatmentId control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents hiddenTreatmentId As Global.System.Web.UI.HtmlControls.HtmlInputHidden

   '''<summary>
   '''dropDownListClinic control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents dropDownListClinic As Global.System.Web.UI.WebControls.DropDownList

   '''<summary>
   '''dropDownPatient control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents dropDownPatient As Global.System.Web.UI.WebControls.DropDownList

   '''<summary>
   '''inputDate control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents inputDate As Global.System.Web.UI.HtmlControls.HtmlInputGenericControl

   '''<summary>
   '''inputDes control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents inputDes As Global.System.Web.UI.HtmlControls.HtmlInputText

   '''<summary>
   '''inputCost control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents inputCost As Global.System.Web.UI.HtmlControls.HtmlInputGenericControl

   '''<summary>
   '''resultSubmit control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents resultSubmit As Global.System.Web.UI.HtmlControls.HtmlGenericControl
End Class
