'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class TreatmentManagement

   '''<summary>
   '''hiddenPatientId control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents hiddenPatientId As Global.System.Web.UI.HtmlControls.HtmlInputHidden

   '''<summary>
   '''hiddenClinicId control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents hiddenClinicId As Global.System.Web.UI.HtmlControls.HtmlInputHidden

   '''<summary>
   '''dropDownListClinic control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents dropDownListClinic As Global.System.Web.UI.WebControls.DropDownList

   '''<summary>
   '''deletedIdInput control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents deletedIdInput As Global.System.Web.UI.HtmlControls.HtmlInputHidden

   '''<summary>
   '''yesButton control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents yesButton As Global.System.Web.UI.HtmlControls.HtmlButton
End Class
